import { Header } from "@/components";
import "./globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { store } from "@/state/store";
import { login } from "@/state/authSlice";
import StateProvider from "@/state/StateProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Idea Spark",
    description: "Generated by Idea Spark",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const cookiesStore = cookies();
    if (cookiesStore.has("token")) {
        const token = cookiesStore.get("token")?.value as string;
        store.dispatch(login(token));
    }

    return (
        <html lang="en">
            <body className={inter.className}>
                <StateProvider>
                    <Header />
                    <main id="main" className="">
                        {children}
                    </main>
                </StateProvider>
            </body>
        </html>
    );
}
